### ISSUE TITLE
Make eep4k the default again so the game doesn't fail to save on the most widely used flashcarts

### ISSUE THREAD

**Issue by thecozies** [Reonu/HackerSM64#130]

**Comment by Reonu** [comment]
#128 made the game require eep16k as the minimum for the save type.

This breaks saving on flashcarts that don't respect the ROM header which is most of them.

Regardless of this, there should be an error screen when there is a save type mismatch. The game should never silently fail to save. If that was implemented, this wouldn't be such a huge issue. But still, even if that was the case, we shouldn't be requiring eep16k

**Comment by FazanaJ** [comment]
Only with Puppycamera enabled

it's EEP4K otherwise

**Comment by Reonu** [comment]
> Only with Puppycamera enabled
> 
> it's EEP4K otherwise

Still, can't you support eep4k with puppycamera? You mentioned something about removing the backup save files right? That would work imo

**Comment by Reonu** [comment]
Or at least implement the error screen but please don't let it just fail to save silently, that's just terrible

**Comment by FazanaJ** [comment]
So testing with PJ64, it's only cutting off the backup, I'd need someone with ED64P to test if the same happens there

If the behaviours the same then I think the issue will be fine for the short term

**Comment by Reonu** [comment]
Isn't it better to just disable the backup rather than let it get cut off?

**Comment by FazanaJ** [comment]
Yeahhh but that involves a bunch of code changes so I'd rather explore other options first.
Especially since EEP16K is clearly proving problematic to begin with so that needs fixing anyway

**Comment by Reonu** [comment]
Would turning `u8 firstBoot` into a bitfield ( `u8 firstBoot: 1`) generate enough free space? Are there any other u8s in the savefile that can be made smaller like this?

**Comment by thecozies** [comment]
gotta keep in mind star tracker too

**Comment by thecozies** [comment]
tho i feel like HackerSM64 should have an official star tracker integration at this point lol

**Comment by Mr-Wiseguy** [comment]
> Would turning u8 firstBoot into a bitfield ( u8 firstBoot: 1) generate enough free space? Are there any other u8s in the savefile that can be made smaller like this?
Only if there are other bitfields to fill the remaining 7 bits of the byte. If there aren't any, then the other 7 bits go unused and it's the same size.

**Comment by Reonu** [comment]
> > Would turning u8 firstBoot into a bitfield ( u8 firstBoot: 1) generate enough free space? Are there any other u8s in the savefile that can be made smaller like this?
> 
> Only if there are other bitfields to fill the remaining 7 bits of the byte. If there aren't any, then the other 7 bits go unused and it's the same size.

`soundMode`and `language` are also bitfields. We can maybe look for more variables that can be turned into bitfields idk

**Comment by Mr-Wiseguy** [comment]
Then that'll work because they're right next to each other; since the other thing to note is that bitfields need to be adjacent fields to share a byte.

**Comment by Reonu** [comment]
is it enough to fix the issue though? (but it should be done regardless lol)
