### ISSUE TITLE
LIST OF SUGGESTED DEFINE DEFAULTS

### ISSUE THREAD

**Issue by arthurtilly** [Reonu/HackerSM64#159]
Should be the final issue that is taken care of right before merge

i think this also kinda needs to be on pc port :flushed:

**Comment by thecozies** [comment]
This should be a thread for all define default toggles

**Comment by thecozies** [comment]
disable interaction indicator from being enabled by default

**Comment by gheskett** [comment]
disable all debug related defines by default (including puppyprint debug)

**Comment by gheskett** [comment]
disable `GROUND_TURNING_AROUND_FIX` by default

**Comment by gheskett** [comment]
Re-enable star checks after refactor is complete

**Comment by thecozies** [comment]
disable `OBJ_OPACITY_BY_CAM_DIST`

**Comment by gheskett** [comment]
`TINY_GOOMBA_ALWAYS_DROPS_COIN` should be disabled by default

**Comment by Reonu** [comment]
`GROUND_TURNING_AROUND_FIX` off please

**Comment by Mr-Wiseguy** [comment]
Addressed in #242
