### ISSUE TITLE
Ukiki falls through the star cage

### ISSUE THREAD

**Issue by Mineqwerty** [Reonu/HackerSM64#167]
When doing the mystery of the monkey cage star, instead of stomping on the top of the cage, ukiki fell straight through. The star was still able to spawn however.

**Comment by MrComit** [comment]
This is fixable by giving bhvUkikiCage the OBJ_FLAG_DONT_CALC_COLL_DIST object flag (tested it myself just now).

**Comment by Axollyon** [comment]
> This is fixable by giving bhvUkikiCage the OBJ_FLAG_DONT_CALC_COLL_DIST object flag (tested it myself just now).

Makes sense, as the collision distance calculation would mean that the cage's collision isn't loaded.

**Comment by axollyon** [comment]
Fixed by #185
