### ISSUE TITLE
BBH crash going through second door to the left of the stairs on the second floor

### ISSUE THREAD

**Issue by Axollyon** [Reonu/HackerSM64#172]
![image](https://user-images.githubusercontent.com/20480418/146317307-d9ce9c40-19dc-4b15-a114-dcb87d828486.png)
Happens on every act, with defines `ENABLE_VANILLA_LEVEL_SPECIFIC_CHECKS`, `KEEP_MARIO_HEAD` enabled, and `PEACH_SKIP`, `UNLOCK_ALL`, `DISABLE_DEMO` disabled
Also, supposedly not actually in `update_parallel_tracking_camera` according to Wiseguy - crash screen inaccuracy?

**Comment by Mr-Wiseguy** [comment]
According to objdump or the map file, the crash actually takes place in offset_rotated:
![image](https://user-images.githubusercontent.com/68165316/146318101-1aec82d7-9748-4c3c-a15a-168f5c139086.png)

**Comment by Axollyon** [comment]
![image](https://user-images.githubusercontent.com/20480418/146320352-f43d2818-0527-4555-adf8-5dc901f56b9d.png)
whatever all this means idk

**Comment by JoshDuMan** [comment]
Looking, Wiseguy is completely correct, it is not initialized. `Vec3f focOffset; = { 0 };` should fix it.

**Comment by Axollyon** [comment]
Fixed in #180
