### ISSUE TITLE
Disabling CLEAR_RAM causes an immediate crash

### ISSUE THREAD

**Issue by thecozies** [Reonu/HackerSM64#189]
Game will start with WOOOAAAAWWWW, but black screen and no crash screen.

**Comment by gheskett** [comment]
This could basically be caused by _anything_. Might be better to push off for a 2.1 release for now if a fix isn't easily determinable.

**Comment by thecozies** [comment]
i agree, though if this is a severe enough issue it could be worth a 2.0.1 release

**Comment by Mr-Wiseguy** [comment]
This is caused by BSS for segments besides main not being properly cleared on boot. It's not really a big deal to leave this on with that in mind, as the alternative would just be zeroing out the memory for each segment's BSS.

**Comment by Mr-Wiseguy** [comment]
Fixed by #297
