### ISSUE TITLE
[QoL] Config Documentation

### ISSUE THREAD

**Issue by thecozies** [Reonu/HackerSM64#191]
These would be good to label for repo accessibility! Should this be in 2.0?

- `START_LEVEL` has no safeguard, if undefined it wont compile
- `START_LEVEL` should have a comment explaining how to get it to work in other levels
- `EXIT_COURSE_LEVEL` should have a comment explaining how to get it to work in other levels

- `DEFAULT_NUM_LIVES` should have a comment for the max number of lives (s8)

**Comment by gheskett** [comment]
All documentation is good documentation; anything that isn't painfully long to add that helps should be added to 2.0 since that's not going to lead to any bugs.

Also yes, `START_LEVEL` should have a safeguard.
