### ISSUE TITLE
Reimplement a configurable WORLD_SCALE define (reassess usage)

### ISSUE THREAD

**Issue by thecozies** [Reonu/HackerSM64#195]
World scale is hardcoded to 1 in `math.s` and should be configurable per hack. This should be a define, and its implementation could use a reassessment as well.

**Comment by thecozies** [comment]
https://github.com/Reonu/HackerSM64/blob/master/asm/math.s#L18

**Comment by Reonu** [comment]
This **must** be fixed before merging with master.

**Comment by Reonu** [comment]
If the asm can be fixed, cool, if not, I'm putting the old `WORLD_SCALE` code back.
