### ISSUE TITLE
TTM Slide coin spawns in wrong location

### ISSUE THREAD

**Issue by Arceveti** [Reonu/HackerSM64#201]
One of the coins in a line formation in the TTM slide spawns on top of an arch instead of on the slide itself:
![image](https://user-images.githubusercontent.com/73617174/146607473-711628ed-a881-4aad-a020-dfe9078e1106.png)
In vanilla, all 5 coins are on the slide.
This is probably just another slope fix thing.

**Comment by axollyon** [comment]
Can confirm - the corresponding macro object is positioned in specifically this spot, which should be below the archway. I'm not sure why `find_floor` would be going upwards like that.
![image](https://user-images.githubusercontent.com/20480418/146610615-d56d6575-2e3f-4cac-9024-6c18a4688b97.png)

**Comment by thecozies** [comment]
![image](https://user-images.githubusercontent.com/79979276/146946321-4f9d8287-feea-4ae3-ad1f-156d3061b68b.png)

# this bug is in master
