### ISSUE TITLE
nonstop stars issues

### ISSUE THREAD

**Issue by thecozies** [Reonu/HackerSM64#258]

**Comment by NyakoFox** [comment]
Keys do not take you out of the level. While I can understand this might be intentional, they should at least play the correct jingle. Instead, collecting a key plays the star collect jingle.

**Comment by gheskett** [comment]
> Keys do not take you out of the level. While I can understand this might be intentional, they should at least play the correct jingle. Instead, collecting a key plays the star collect jingle.

This is a vanilla thing I think. We'll need to rewrite the way it works if we want it to work with nonstop stars.

**Comment by thecozies** [comment]
hmmm i feel like keys should take you out of the level using a separate define

so the way vanilla and most hacks are designed, have bowser as its own level with no way out. so if you were getting a key from bowser, you most likely want it to warp you out of there. so having an option of `KEYS_EXIT_LEVEL` might fix this

**Comment by thecozies** [comment]
and yeah i think the key song should play if reasonably possible

**Comment by Arceveti** [comment]
Fixed in #299
