### ISSUE TITLE
credits text is off from vanilla

### ISSUE THREAD

**Issue by thecozies** [Reonu/HackerSM64#265]
looks to be off from timing and off with positioning

**Comment by thecozies** [comment]
![bad](https://user-images.githubusercontent.com/79979276/147619027-5e621397-8e98-4ada-a683-cc6eb7ff8040.png)

compare that to vanilla

![vanilla](https://user-images.githubusercontent.com/79979276/147619043-49e41524-80d5-4798-8b62-f2b15f0b4975.png)

**Comment by Arceveti** [comment]
Fixed by #301
