### ISSUE TITLE
Extended Bounds Mode 3 Crash at: Main Pool Free

### ISSUE THREAD

**Issue by dariodimarcoberardinoRetroHax** [Reonu/HackerSM64#287]
Like the Title explains when selecting the Third Extended bounds Mode which allows for 4 times larger levels compared to Vanilla causes a crash when entering custom Levels and also when entering mario 64s original levels even then it sometimes crashes tho a weird issue is that the castles can be entered without crashing tho i dont know if its a fault on my end or on how the extended bounds work but itll be great find out how to fix this error heres a picture btw

Here are pictures with all 4 Pages of the Crash Handler:
cant show the crash handler on console tho its basically the same because of a broken capture card and i dont feel like recording my monitor hopefully thats understandable :3 Pictures were taken on Mupen64 Plus Next the retroarch libretro core

![page00](https://user-images.githubusercontent.com/69952967/148220937-f9ee0aad-d135-421b-aeec-d8673772fc5e.png)
![page01](https://user-images.githubusercontent.com/69952967/148220940-e964a9f0-1d56-4b67-bce7-146d12530317.png)
![page02](https://user-images.githubusercontent.com/69952967/148220941-b0a7895b-3abd-45f1-b6d8-672cb9941a2b.png)
![page03](https://user-images.githubusercontent.com/69952967/148220946-d2372012-ac3d-4613-b124-d5ddbb6547bc.png)
![page04](https://user-images.githubusercontent.com/69952967/148220947-d18aa8f4-244c-4a05-99a5-f703583b10d4.png)
r

**Comment by Reonu** [comment]
This looks like you ran out of RAM. Is `USE_EXT_RAM` defined in `include/segments.h`?

**Comment by Reonu** [comment]
I just entered every vanilla level in the game in ext bounds mode 3 and there were no crashes.

**Comment by dariodimarcoberardinoRetroHax** [comment]
That was the first thing i did and yes this also causes an error heres is my <segemnts.h> well a part of it :P

<#define USE_EXT_RAM
// Calculate total amount of RAM
#ifndef USE_EXT_RAM
#define TOTAL_RAM_SIZE  (RAM_1MB * 4)
#else
#define TOTAL_RAM_SIZE  (RAM_1MB * 8)
#endif>

If you want i can also give you my blender file but also literally just importing a simple cube as a level with the extended bounds mode 3 applied seems to crash the game

**Comment by Mr-Wiseguy** [comment]
Most likely fixed by #289, please pull those changes and see if the issue still happens.

**Comment by dariodimarcoberardinoRetroHax** [comment]
Yup! :D Everything works now! :3 Thank you Guys! >w<

**Comment by Reonu** [comment]
Fixed with #289
