### ISSUE TITLE
File select menu state change crash

### ISSUE THREAD

**Issue by Arceveti** [Reonu/HackerSM64#298]
SCORE -> COPY:
Crash after animation:
![image](https://user-images.githubusercontent.com/73617174/149044796-b4bf84ea-347f-4c05-9262-044828d322ee.png)
![image](https://user-images.githubusercontent.com/73617174/149044834-67fd8bce-eb99-4186-8f3a-f9a4d3c73a14.png)
![image](https://user-images.githubusercontent.com/73617174/149044867-54fd5705-3bbd-484e-9504-defb6977ec02.png)

SCORE -> ERASE:
Crash after animation:
![image](https://user-images.githubusercontent.com/73617174/149044994-f3fe3520-cbb4-46f9-8808-8841f03ea225.png)
![image](https://user-images.githubusercontent.com/73617174/149045024-bd3bd7f8-b7f3-4784-a19d-9ab69945686a.png)
![image](https://user-images.githubusercontent.com/73617174/149045055-ef2b1bad-7563-4154-a0c5-665784de9723.png)

COPY  -> SCORE:
No issue

COPY -> ERASE:
Same crash as SCORE -> ERASE.

ERASE -> SCORE:
No issue.

ERASE -> COPY:
No crash, but the buttons no longer work.

**Comment by Reonu** [comment]
bruh

**Comment by Reonu** [comment]
I will bisect this

**Comment by Arceveti** [comment]
Fixed by #300
