### ISSUE TITLE
Debug level select freezes on the 6th time entering a level on RetroArch

### ISSUE THREAD

**Issue by Arceveti** [Reonu/HackerSM64#67]
When debug level select is enabled, entering 6 levels in one game session (they can be different levels or the same levels) freezes on the 6th level with no crash screen. The first 5 levels load normally. This happens RetroArch but not PJ64. Entering a level via painting does not count toward the 6 levels.

**Comment by Reonu** [comment]
we all know the answer but

does it crash on console?

**Comment by Arceveti** [comment]
This was caused by gTlbSegments[i] and gTlbEntries not being cleared for certain segments in unmap_tlbs(). It's fixed in  in https://github.com/Reonu/HackerSM64/pull/96
