### ISSUE TITLE
[Lighting Engine] Point lights are broken, they seem to always come from under the world

### ISSUE THREAD

**Issue by Reonu** [Reonu/HackerSM64#835]
When using point lights, they seem to more often than not come from "below the ground" rather than their intended position, and they only affect faces that are facing downwards. Sometimes they seem to behave as intended, but it's rare.

Here's an example from when I tried to use point lights in RHDC.ppt. I added a blue-ish point light in the middle of the office. As you can see here it's only affecting faces that are facing downwards, such as the ceiling, or the part of the shelf above the books. 
![imagen](https://github.com/user-attachments/assets/62fc6e92-868f-45bc-876b-9c798092d207)

**Comment by gheskett** [comment]
UPDATE: This is reportedly only happening to objects (RHDC.ppt office is also apparently an object). Could it have something to do with geo processing order maybe?

**Comment by gheskett** [comment]
Turns out this is a fast64 issue, `gsSPLoadGeometryMode` zeroizes everything it doesn't specify to set.
